server:
  port: 8088

tencentcloudapi:
  # 你的 secretId
  secretId: AKIDmSwGOM8kBPRGs7C7pJadWDj3FH5qVBtQ
  # 你的 secretKey
  secretKey: QfhYDfu09HI9pKchdO4fFfuwpaDgAhCe
  # 请求官方地址 不变
  endpoint: iai.tencentcloudapi.com
  #地域 可不变
  region: ap-beijing

spring:
  datasource:
    url: jdbc:mysql://1.12.238.58:3306/myadmin?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    username: admin
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

mybatis:
  typeAliasesPackage: com.face.bean
  mapperLocations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true